<?php
$books = [
    [
        'title' => 'A Theory of Lay Ministry Praxis',
        'slug' => 'book1',
        'cover' => 'images/books/book1.png',
        'date' => '17 December, 2024',
        'tag' => 'Lay Ministry',
        'summary' => 'A ground-breaking study on how lay people in Kenyan Assemblies of God serve each other and grow through identity in Christ.',
        'purchase_url' => 'https://www.amazon.co.uk/s?k=A+Theory+Of+Lay+Ministry+Praxis&crid=3I1QYCBNC5JNN&sprefix=a+theory+of+lay+ministry+praxis%2Caps%2C101&ref=nb_sb_noss_2',
    ],
    [
        'title' => 'The Miracle of a Genuine Confession',
        'slug' => 'miracle-of-genuine-confession',
        'cover' => 'images/books/miracle.jpg',
        'date' => '4 June, 2026',
        'tag' => 'Spiritual Growth',
        'summary' => 'A clear guide to true confession as a whole-person response to God involving the mind, heart, and hands.',
        'purchase_url' => 'https://a.co/d/04BkgX0O',
    ],
    [
        'title' => 'Calling Of God and Its Coordinates',
        'slug' => 'calling-of-God',
        'cover' => 'images/books/calling.jpg',
        'date' => '4 March, 2026',
        'tag' => 'Calling',
        'summary' => 'A practical invitation to receive, refine, and realise God-given mandate through the 12 Cs of Christ.',
        'purchase_url' => 'https://a.co/d/0gCSrNoj',
    ],
    [
        'title' => 'Body Over Brand',
        'slug' => 'body-over-brand',
        'cover' => 'images/books/bodyOverBrand.jpg',
        'date' => '22 May, 2026',
        'tag' => 'Church Life',
        'summary' => 'A theological call for the church to recover its identity as the living Body of Christ rather than an image-driven brand.',
        'purchase_url' => 'https://a.co/d/0g9OCXNs',
    ],
    [
        'title' => 'The 12 Cs of Christ',
        'slug' => '12cs',
        'cover' => 'images/books/12Cs.jpg',
        'date' => '23 Jul, 2026',
        'tag' => 'Discipleship',
        'summary' => 'A Christ-centred framework for spiritual formation, discipleship, ministry, and mission.',
        'purchase_url' => 'https://a.co/d/05LnTUZS',
    ],
    [
        'title' => 'The Look',
        'slug' => 'look',
        'cover' => 'images/books/Look.jpg',
        'date' => '10 Oct, 2006',
        'tag' => 'Personal Growth',
        'summary' => 'A guide to dressing from the inside out, encouraging readers to respect their body, taste, and personal style.',
        'purchase_url' => 'https://a.co/d/0iQmr9gJ',
    ],
    [
        'title' => 'Marriage Made in Heaven',
        'slug' => 'marriage-made-in-heaven',
        'cover' => 'images/books/MarriageMadeInHeaven.jpg',
        'date' => '1 March, 2026',
        'tag' => 'Marriage',
        'summary' => 'A pastoral and practical framework for discerning wisely and building a Christ-centred marriage.',
        'purchase_url' => 'https://a.co/d/01qzg89x',
    ],
    [
        'title' => 'When Heaven Touches Earth',
        'slug' => 'when-heaven-touches-earth',
        'cover' => 'images/books/WhenHeavenTouchesEarth.jpg',
        'date' => '15 December, 2025',
        'tag' => 'Faith',
        'summary' => 'A practical triad of keys for understanding faith, miracles, transformation, and the sovereignty of God.',
        'purchase_url' => 'https://a.co/d/02RupL22',
    ],
    [
        'title' => 'Prayer That Works',
        'slug' => 'prayer-that-works',
        'cover' => 'images/books/prayer-that-works.jpg',
        'date' => '26 May, 2026',
        'tag' => 'Prayer',
        'summary' => 'A steady guide to effectual prayer through asking, searching, and knocking with ethical integrity.',
        'purchase_url' => 'https://a.co/d/0fdkrIEv',
    ],
    [
        'title' => 'The Pasis Model',
        'slug' => 'pasis-model',
        'cover' => 'images/books/pasis-model.jpg',
        'date' => '25 May, 2026',
        'tag' => 'Spiritual Gifts',
        'summary' => 'A practical handbook for discovering, testing, confirming, and activating spiritual gifts with confidence.',
        'purchase_url' => 'https://a.co/d/0ezWZY8f',
    ],
    [
        'title' => 'Kingdom Leadership of Empowering Stewards',
        'slug' => 'kingdom-leadership',
        'cover' => 'images/books/kingdom-leadership.jpg',
        'date' => '3 Feb, 2026',
        'tag' => 'Leadership',
        'summary' => 'A manifesto for Kingdom leadership rooted in scripture, Spirit-formed character, and empowering stewardship.',
        'purchase_url' => 'https://a.co/d/03OMD6uw',
    ],
];
